# Change these first
owner: miko-radio # Your GitHub organization or username, where this repository lives
repo: miko-radio.github.io # The name of this repository

sites:
  - name: miko
    url: https://mikoradio.com/
  - name: Dashboard
    url: http://ws.mikoradio.com/
  - name: korivash
    url: https://www.korivash.com/

status-website:
  # Add your custom domains names, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: miko-radio.github.io
  # baseUrl: /uptime-monitor
  logoUrl: https://raw.githubusercontent.com/Miko-Radio/miko-radio.github.io/main/miko.webp
  name: Miko Radio
  theme: night
  introTitle: "Miko Radio Resources. Powered by github actions."
  introMessage: Miko Radio Resources, which are down, and which are broken here!
  navbar:
    - title: Uptime
      href: /
    - title: GitHub
      href: https://github.com/$OWNER
    - title: Community
      href: https://discord.gg/VhAj8K4C6F
      
theme: dark
skipDescriptionUpdate: true
skipTopicsUpdate: true

workflowSchedule:
  graphs: "*/5 * * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "*/5 * * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
