name: Send Discord Message

on:
  push:
    branches:
      - main

jobs:
  send-discord-message:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch README content
      id: readme
      run: |
        readme_content=$(cat README.md | head -n 40)
        echo "::set-output name=content::$readme_content"

    - name: Send message to Discord
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        content="${{ steps.readme.outputs.content }}"
        curl -H "Content-Type: application/json" \
             -d '{
                   "embeds": [
                     {
                       "title": "New Push to Miko Radio Repository",
                       "description": "'"${content}"'",
                       "color": 5814783,
                       "fields": [
                         {
                           "name": "Repository",
                           "value": "${{ github.repository }}"
                         },
                         {
                           "name": "Committer",
                           "value": "${{ github.actor }}"
                         },
                         {
                           "name": "Commit Message",
                           "value": "${{ github.event.head_commit.message }}"
                         }
                       ]
                     }
                   ]
                 }' \
             $DISCORD_WEBHOOK_URL



