name: Send Discord Message

on:
  push:
    branches:
      - main

jobs:
  send-discord-message:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch README content
      id: readme
      run: |
        readme_content=$(curl -s https://api.github.com/repos/Miko-Radio/miko-radio.github.io/readme | jq -r .content | base64 --decode | head -n 20)
        echo "::set-output name=content::$readme_content"

    - name: Send message to Discord
      run: |
        content="${{ steps.readme.outputs.content }}"
        curl -H "Content-Type: application/json" \
             -d '{
                   "embeds": [
                     {
                       "title": "New Push to Miko Radio Repository",
                       "description": "'"${content}"'",
                       "color": 5814783,
                       "fields": [
                         {
                           "name": "Repository",
                           "value": "${{ github.repository }}"
                         },
                         {
                           "name": "Committer",
                           "value": "${{ github.actor }}"
                         },
                         {
                           "name": "Commit Message",
                           "value": "${{ github.event.head_commit.message }}"
                         }
                       ]
                     }
                   ]
                 }' \
             https://discord.com/api/webhooks/1246657089355513917/RELX_TPIcUu2UN2HHOylZXQSnrqt8HAogJs3xOWMvJJzLoPPnUVsSlW5u62BFkVkrIyD


