name: Update Discord Message

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/10 * * * *'

jobs:
  send-discord-message:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch site content
      id: fetch_content
      run: |
        site_content=$(curl -s https://miko-radio.github.io/)
        live_status=$(echo "$site_content" | grep -oP '(?<=<h1>)[^<]+') # Adjust the grep pattern based on actual HTML structure
        echo "::set-output name=live_status::$live_status"
        echo "Fetched live status: $live_status"

    - name: Print fetched content for debugging
      run: |
        echo "Fetched live status: ${{ steps.fetch_content.outputs.live_status }}"

    - name: Send live status to Discord
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        live_status="${{ steps.fetch_content.outputs.live_status }}"
        # Escape double quotes and newlines
        live_status=$(echo "$live_status" | sed 's/"/\\"/g' | sed ':a;N;$!ba;s/\n/ /g')
        echo "Sending live status to Discord: $live_status"
        curl -H "Content-Type: application/json" \
             -d "{\"embeds\": [{\"title\": \"Live Status Update\",\"description\": \"$live_status\",\"color\": 5814783}]}" \
             $DISCORD_WEBHOOK_URL

    - name: Send message to other webhook
      run: |
        site_content=$(curl -s https://miko-radio.github.io/)
        echo "Sending site content to the other webhook: $site_content"
        curl -H "Content-Type: application/json" \
             -d "{\"embeds\": [{\"title\": \"Update to Miko Radio Repository\",\"description\": \"$site_content\",\"color\": 5814783}]}" \
             https://discord.com/api/webhooks/1189802524123877456/LHiCOQesQH76ky9zPT_6adK5MDQ8rwnBx8Zq6SlG4IDP2GASaeO-zSr_0_dSp-KkApcY/github











