name: Update Discord Message

on:
  push:
    branches:
      - main
  schedule:
    - cron: '* * * * *'

jobs:
  send-discord-message:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch site content
      id: fetch_site
      run: |
        site_content=$(wget -qO- https://miko-radio.github.io/)
        echo "::set-output name=site::$site_content"
        echo "Fetched site content: $site_content"

    - name: Print fetched content for debugging
      run: |
        echo "Fetched site content: ${{ steps.fetch_site.outputs.site }}"

    - name: Send site content to Discord
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        content="${{ steps.fetch_site.outputs.site }}"
        # Escape double quotes and newlines using jq
        content=$(jq -Rs '.' <<< "$content")
        echo "Sending site content to Discord: $content"
        curl -H "Content-Type: application/json" \
             -d "{\"embeds\": [{\"title\": \"Site Update\",\"description\": $content,\"color\": 5814783}]}" \
             $DISCORD_WEBHOOK_URL

















