name: Update Discord Message

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'

jobs:
  send-discord-message:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch site content
      id: fetch_site
      run: |
        site_content=$(wget -qO- https://miko-radio.github.io/)
        echo "::set-output name=site::$site_content"

    - name: Print fetched content for debugging
      run: |
        echo "Fetched site content: ${{ steps.fetch_site.outputs.site }}"

    - name: Send site content to Discord
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        content="${{ steps.fetch_site.outputs.site }}"
        # Properly escape the fetched HTML content
        escaped_content=$(echo "$content" | jq -Rsa .)
        echo "Sending site content to Discord: $escaped_content"
        curl -H "Content-Type: application/json" \
             -d "{\"embeds\": [{\"title\": \"Site Update\",\"description\": $escaped_content,\"color\": 5814783}]}" \
             $DISCORD_WEBHOOK_URL




















