name: Send Discord Message

on:
  push:
    branches:
      - main

jobs:
  send-discord-message:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch site content
      id: fetch_content
      run: |
        site_content=$(curl -s https://miko-radio.github.io/)
        echo "::set-output name=content::$site_content"
        echo "Fetched content: $site_content"

    - name: Print fetched content for debugging
      run: |
        echo "Fetched content: ${{ steps.fetch_content.outputs.content }}"

    - name: Send message to Discord
      run: |
        content="${{ steps.fetch_content.outputs.content }}"
        # Escape double quotes and newlines
        content=$(echo "$content" | sed 's/"/\\"/g' | sed ':a;N;$!ba;s/\n/ /g')
        echo "Sending content to Discord: $content"
        curl -H "Content-Type: application/json" \
             -d "{\"embeds\": [{\"title\": \"New Push to Miko Radio Repository\",\"description\": \"$content\",\"color\": 5814783}]}" \
             https://discord.com/api/webhooks/1246657089355513917/RELX_TPIcUu2UN2HHOylZXQSnrqt8HAogJs3xOWMvJJzLoPPnUVsSlW5u62BFkVkrIyD







