name: Update Discord with Uptime Graph

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'

jobs:
  send-uptime-graph:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch README content
      id: fetch_readme
      run: |
        readme_content=$(cat README.md)
        echo "::set-output name=content::$readme_content"
    
    - name: Fetch latest uptime graph
      id: fetch_graph
      run: |
        graph_url="https://raw.githubusercontent.com/${{ github.repository }}/HEAD/graphs/uptime-graph.svg"
        echo "::set-output name=graph_url::$graph_url"

    - name: Print fetched content for debugging
      run: |
        echo "Fetched README content: ${{ steps.fetch_readme.outputs.content }}"
        echo "Uptime graph URL: ${{ steps.fetch_graph.outputs.graph_url }}"

    - name: Send site content and graph to Discord
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        content="${{ steps.fetch_readme.outputs.content }}"
        graph_url="${{ steps.fetch_graph.outputs.graph_url }}"
        # Properly escape the fetched content
        escaped_content=$(echo "$content" | jq -Rsa .)
        echo "Sending README content and uptime graph to Discord"
        curl -H "Content-Type: application/json" \
             -d "{
                   \"embeds\": [
                     {
                       \"title\": \"Uptime Status Update\",
                       \"description\": $escaped_content,
                       \"color\": 5814783,
                       \"image\": {
                         \"url\": \"$graph_url\"
                       }
                     }
                   ]
                 }" \
             $DISCORD_WEBHOOK_URL






















