name: Update Discord Message

on:
  push:
    branches:
      - main
  schedule:
    - cron: '* * * * *'

jobs:
  send-discord-message:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch README content
      id: fetch_content
      run: |
        readme_content=$(cat README.md)
        echo "::set-output name=content::$readme_content"
        echo "Fetched README content: $readme_content"

    - name: Print fetched content for debugging
      run: |
        echo "Fetched README content: ${{ steps.fetch_content.outputs.content }}"

    - name: Send README to Discord
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        content="${{ steps.fetch_content.outputs.content }}"
        # Escape double quotes and newlines
        content=$(echo "$content" | sed 's/"/\\"/g' | sed ':a;N;$!ba;s/\n/ /g')
        echo "Sending README content to Discord: $content"
        curl -H "Content-Type: application/json" \
             -d "{\"embeds\": [{\"title\": \"README Update\",\"description\": \"$content\",\"color\": 5814783}]}" \
             $DISCORD_WEBHOOK_URL

    - name: Send message to other webhook
      run: |
        site_content=$(curl -s https://miko-radio.github.io/)
        echo "Sending site content to the other webhook: $site_content"
        curl -H "Content-Type: application/json" \
             -d "{\"embeds\": [{\"title\": \"Update to Miko Radio Repository\",\"description\": \"$site_content\",\"color\": 5814783}]}" \
             https://discord.com/api/webhooks/1189802524123877456/LHiCOQesQH76ky9zPT_6adK5MDQ8rwnBx8Zq6SlG4IDP2GASaeO-zSr_0_dSp-KkApcY/github














