name: Update Discord with Uptime Graph

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'

jobs:
  send_discord_message:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch README content
      id: fetch_readme
      run: |
        readme_content=$(cat README.md)
        echo "::set-output name=content::$readme_content"
    
    - name: Fetch latest uptime graph
      id: fetch_graph
      run: |
        graph_url="https://status.mikoradio.com/graphs/uptime-graph.svg"
        echo "::set-output name=graph_url::$graph_url"

    - name: Extract status summary
      id: extract_summary
      run: |
        summary=$(grep -A 10 '<!--start: status pages-->' README.md | grep -v '<!--start: status pages-->')
        summary="${summary:0:2000}"  # Limit summary to 2000 characters to fit Discord's limits
        echo "::set-output name=summary::$summary"

    - name: Print fetched content for debugging
      run: |
        echo "Fetched README content: ${{ steps.fetch_readme.outputs.content }}"
        echo "Uptime graph URL: ${{ steps.fetch_graph.outputs.graph_url }}"
        echo "Extracted summary: ${{ steps.extract_summary.outputs.summary }}"

    - name: Send site content and graph to Discord
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        summary="${{ steps.extract_summary.outputs.summary }}"
        # Properly escape the fetched content
        escaped_summary=$(echo "$summary" | jq -Rs .)
        echo "Sending uptime graph and site summary to Discord"
        curl -H "Content-Type: application/json" \
             -d "{
                   \"embeds\": [
                     {
                       \"title\": \"Miko Radio Uptime Status Update\",
                       \"description\": \"Here is the latest status update for Miko Radio.\",
                       \"color\": 5814783,
                       \"fields\": [
                         {
                           \"name\": \"Website\",
                           \"value\": \"[Miko Radio](https://mikoradio.com)\",
                           \"inline\": true
                         },
                         {
                           \"name\": \"Status Page\",
                           \"value\": \"[Miko Radio Status](https://status.mikoradio.com)\",
                           \"inline\": true
                         },
                         {
                           \"name\": \"Latest Uptime Graph\",
                           \"value\": \"[View Graph](https://status.mikoradio.com/graphs/uptime-graph.svg)\",
                           \"inline\": false
                         },
                         {
                           \"name\": \"Summary\",
                           \"value\": $escaped_summary,
                           \"inline\": false
                         }
                       ],
                       \"image\": {
                         \"url\": \"https://status.mikoradio.com/graphs/uptime-graph.svg\"
                       }
                     }
                   ]
                 }" \
             $DISCORD_WEBHOOK_URL











   




































