name: Update Discord with Uptime Graph

on:
  push:
    branches:
      - main

jobs:
  send_discord_message:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch status page content
      id: fetch_status
      run: |
        status_content=$(curl -s https://status.mikoradio.com/)
        echo "Fetched status content: $status_content"
        echo "::set-output name=status::$status_content"

    - name: Extract status and graph URL
      id: extract_info
      run: |
        status="${{ steps.fetch_status.outputs.status }}"
        echo "Status content: $status"
        operational=$(echo "$status" | grep -o 'All systems operational')
        partial=$(echo "$status" | grep -o 'Partial Outage')
        graph_url=$(echo "$status" | grep -oP '(?<=<img src=")[^"]*uptime-graph[^"]*')
        echo "Operational: $operational"
        echo "Partial: $partial"
        echo "Graph URL: $graph_url"
        
        if [[ -n "$operational" ]]; then
          color=3066993 # Green
          status_text="All systems operational"
        elif [[ -n "$partial" ]]; then
          color=15105570 # Orange
          status_text="Partial Outage"
        else
          color=15158332 # Red
          status_text="Outage detected"
        fi

        if [[ -z "$graph_url" ]]; then
          graph_url="https://via.placeholder.com/600x400.png?text=No+Graph+Available"
        else
          graph_url="https://status.mikoradio.com/$graph_url"
        fi

        echo "::set-output name=color::$color"
        echo "::set-output name=status_text::$status_text"
        echo "::set-output name=graph_url::$graph_url"

    - name: Print extracted information for debugging
      run: |
        echo "Embed color: ${{ steps.extract_info.outputs.color }}"
        echo "Status text: ${{ steps.extract_info.outputs.status_text }}"
        echo "Graph URL: ${{ steps.extract_info.outputs.graph_url }}"

    - name: Send status and graph to Discord
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        color="${{ steps.extract_info.outputs.color }}"
        status_text="${{ steps.extract_info.outputs.status_text }}"
        graph_url="${{ steps.extract_info.outputs.graph_url }}"
        echo "Sending status and graph to Discord"
        curl -H "Content-Type: application/json" \
             -d "{
                   \"embeds\": [
                     {
                       \"title\": \"Miko Radio Uptime Status Update\",
                       \"description\": \"$status_text\",
                       \"color\": $color,
                       \"image\": {
                         \"url\": \"$graph_url\"
                       }
                     }
                   ]
                 }" \
             $DISCORD_WEBHOOK_URL





























