name: Update Discord with Uptime Graph

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/25 * * * *'

jobs:
  send_discord_message:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch README content
      id: fetch_readme
      run: |
        readme_content=$(cat README.md)
        echo "::set-output name=content::$readme_content"
    
    - name: Fetch latest uptime graph
      id: fetch_graph
      run: |
        graph_url="https://raw.githubusercontent.com/${{ github.repository }}/HEAD/graphs/uptime-graph.svg"
        echo "::set-output name=graph_url::$graph_url"

    - name: Determine Status and Set Embed Color
      id: determine_status
      run: |
        # Fetch the status of the site (this is an example, adjust as needed)
        status=$(curl -s https://status.mikoradio.com/api/status)
        if [[ "$status" == *"All systems operational"* ]]; then
          echo "::set-output name=color::3066993" # Green for online
        elif [[ "$status" == *"Partial Outage"* ]]; then
          echo "::set-output name=color::15105570" # Orange for partial outage
        else
          echo "::set-output name=color::15158332" # Red for outage
        fi

    - name: Print fetched content for debugging
      run: |
        echo "Fetched README content: ${{ steps.fetch_readme.outputs.content }}"
        echo "Uptime graph URL: ${{ steps.fetch_graph.outputs.graph_url }}"
        echo "Embed color: ${{ steps.determine_status.outputs.color }}"

    - name: Send site content and graph to Discord
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        content="${{ steps.fetch_readme.outputs.content }}"
        graph_url="${{ steps.fetch_graph.outputs.graph_url }}"
        color="${{ steps.determine_status.outputs.color }}"
        # Properly escape the fetched content
        escaped_content=$(echo "$content" | jq -Rsa .)
        echo "Sending README content and uptime graph to Discord"
        curl -H "Content-Type: application/json" \
             -d "{
                   \"embeds\": [
                     {
                       \"title\": \"Miko Radio Uptime Status Update\",
                       \"description\": \"Here is the latest status update for Miko Radio.\",
                       \"color\": $color,
                       \"image\": {
                         \"url\": \"$graph_url\"
                       }
                     }
                   ]
                 }" \
             $DISCORD_WEBHOOK_URL

























