name: Update Discord with Uptime Graph

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/1 * * * *'

jobs:
  send_discord_message:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch README content
      id: fetch_readme
      run: |
        readme_content=$(cat README.md)
        echo "::set-output name=content::$readme_content"
    
    - name: Fetch latest uptime graph
      id: fetch_graph
      run: |
        graph_url="https://raw.githubusercontent.com/${{ github.repository }}/HEAD/graphs/uptime-graph.svg"
        echo "::set-output name=graph_url::$graph_url"

    - name: Print fetched content for debugging
      run: |
        echo "Fetched README content: ${{ steps.fetch_readme.outputs.content }}"
        echo "Uptime graph URL: ${{ steps.fetch_graph.outputs.graph_url }}"

    - name: Send site content and graph to Discord
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        content="${{ steps.fetch_readme.outputs.content }}"
        graph_url="${{ steps.fetch_graph.outputs.graph_url }}"
        # Properly escape the fetched content
        escaped_content=$(echo "$content" | jq -Rsa .)
        echo "Sending README content and uptime graph to Discord"
        curl -H "Content-Type: application/json" \
             -d "{
                   \"embeds\": [
                     {
                       \"title\": \"Miko Radio Uptime Status Update\",
                       \"description\": \"Here is the latest status update for Miko Radio.\",
                       \"color\": 5814783,
                       \"fields\": [
                         {
                           \"name\": \"Website\",
                           \"value\": \"[Miko Radio](https://mikoradio.com)\",
                           \"inline\": true
                         },
                         {
                           \"name\": \"Status Page\",
                           \"value\": \"[Miko Radio Status](https://status.mikoradio.com)\",
                           \"inline\": true
                         },
                         {
                           \"name\": \"Latest Uptime Graph\",
                           \"value\": \"[View Graph]($graph_url)\",
                           \"inline\": false
                         },
                         {
                           \"name\": \"Uptime\",
                           \"value\": \"![Uptime CI](https://github.com/miko-radio/miko-radio.github.io/workflows/Uptime%20CI/badge.svg)\",
                           \"inline\": true
                         },
                         {
                           \"name\": \"Response Time\",
                           \"value\": \"![Response Time CI](https://github.com/miko-radio/miko-radio.github.io/workflows/Response%20Time%20CI/badge.svg)\",
                           \"inline\": true
                         },
                         {
                           \"name\": \"Graphs\",
                           \"value\": \"![Graphs CI](https://github.com/miko-radio/miko-radio.github.io/workflows/Graphs%20CI/badge.svg)\",
                           \"inline\": true
                         },
                         {
                           \"name\": \"Static Site\",
                           \"value\": \"![Static Site CI](https://github.com/miko-radio/miko-radio.github.io/workflows/Static%20Site%20CI/badge.svg)\",
                           \"inline\": true
                         },
                         {
                           \"name\": \"Summary\",
                           \"value\": \"![Summary CI](https://github.com/miko-radio/miko-radio.github.io/workflows/Summary%20CI/badge.svg)\",
                           \"inline\": true
                         }
                       ],
                       \"image\": {
                         \"url\": \"$graph_url\"
                       }
                     }
                   ]
                 }" \
             $DISCORD_WEBHOOK_URL


































