name: Update Discord with Uptime Graph

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/1 * * * *'

jobs:
  send_discord_message:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch README content
      id: fetch_readme
      run: |
        readme_content=$(cat README.md)
        echo "::set-output name=content::$readme_content"

    - name: Fetch latest uptime graph
      id: fetch_graph
      run: |
        graph_url="https://raw.githubusercontent.com/${{ github.repository }}/HEAD/graphs/uptime-graph.svg"
        echo "::set-output name=graph_url::$graph_url"

    - name: Fetch site summary
      id: fetch_summary
      run: |
        summary=$(wget -qO- https://status.mikoradio.com | pup 'section.summary json{}')
        echo "::set-output name=summary::$summary"

    - name: Print fetched content for debugging
      run: |
        echo "Fetched README content: ${{ steps.fetch_readme.outputs.content }}"
        echo "Uptime graph URL: ${{ steps.fetch_graph.outputs.graph_url }}"
        echo "Site summary: ${{ steps.fetch_summary.outputs.summary }}"

    - name: Send site content and graph to Discord
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        content="${{ steps.fetch_readme.outputs.content }}"
        graph_url="${{ steps.fetch_graph.outputs.graph_url }}"
        summary="${{ steps.fetch_summary.outputs.summary }}"
        # Properly escape the fetched content
        escaped_content=$(echo "$content" | jq -Rsa .)
        escaped_summary=$(echo "$summary" | jq -Rsa .)
        echo "Sending README content, uptime graph, and site summary to Discord"
        curl -H "Content-Type: application/json" \
             -d "{
                   \"embeds\": [
                     {
                       \"title\": \"Miko Radio Uptime Status Update\",
                       \"description\": \"Here is the latest status update for Miko Radio.\",
                       \"color\": 5814783,
                       \"fields\": [
                         {
                           \"name\": \"Website\",
                           \"value\": \"[Miko Radio](https://mikoradio.com)\",
                           \"inline\": true
                         },
                         {
                           \"name\": \"Status Page\",
                           \"value\": \"[Miko Radio Status](https://status.mikoradio.com)\",
                           \"inline\": true
                         },
                         {
                           \"name\": \"Latest Uptime Graph\",
                           \"value\": \"![View Graph]($graph_url)\",
                           \"inline\": false
                         },
                         {
                           \"name\": \"Summary\",
                           \"value\": $escaped_summary,
                           \"inline\": false
                         }
                       ],
                       \"image\": {
                         \"url\": \"$graph_url\"
                       }
                     }
                   ]
                 }" \
             $DISCORD_WEBHOOK_URL







   




































